sudo: required
services:
  - docker

before_install:
  - docker build -t sampriyadarshi/docker-react -f Dockerfile.dev .

script:
  - docker run sampriyadarshi/docker-react npm run test -- --coverage
